In [1]:
import pandas as pd
%reload_kedro

[05/09/23 10:55:59] INFO     Resolved project path as: C:\kedro_work\weather_aus\weather-aus.       ]8;id=915807;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=901651;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py#134\134]8;;\
                             To set a different path, run '%reload_kedro <project_root>'

[05/09/23 10:56:01] INFO     Kedro project weather_aus                                              ]8;id=863375;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=481515;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py#103\103]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=175568;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=895909;file://C:\kedro_work\venv\lib\site-packages\kedro\ipython\__init__.py#104\104]8;;\
                             'pipelines'

In [2]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\kedro_work\venv\lib\site-packages (1.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.17.3 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: joblib>=1.1.1 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.10.1)

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
catalog.list()

['weather_aus_raw',
 'df1',
 'df1_treat_training_data',
 'X_training',
 'y_training',
 'X_training_le',
 'logreg',
 'y_pred_train',
 'y_pred_test',
 'r2_score_train',
 'r2_score_test',
 'parameters',
 'params:test_size',
 'params:random_state',
 'params:features']

In [4]:
df=catalog.load("weather_aus_raw")

                    INFO     Loading data from 'weather_aus_raw' (CSVDataSet)...                ]8;id=836715;file://C:\kedro_work\venv\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=269634;file://C:\kedro_work\venv\lib\site-packages\kedro\io\data_catalog.py#343\343]8;;\

In [5]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [6]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\kedro_work\venv\lib\site-packages (3.7.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: numpy>=1.20 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (1.24.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (4.39.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (1.0.7)
Requirement already satisfied: pillow>=6.2.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (9.5.0)
Requirement already satisfied: cycler>=0.10 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: six>=1.5 in c:\kedro_work\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
pip install seaborn

Requirement already satisfied: seaborn in c:\kedro_work\venv\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\kedro_work\venv\lib\site-packages (from seaborn) (1.24.3)
Requirement already satisfied: pandas>=0.25 in c:\kedro_work\venv\lib\site-packages (from seaborn) (2.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\kedro_work\venv\lib\site-packages (from seaborn) (3.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.0.7)
Requirement already satisfied: pyparsing>=2.3.1 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.39.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\kedro_work\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)
Requirement already satisfied: tzdata>=2022.1 in c:\kedro_work\venv\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: pytz>=2020.1 in c:\kedro_work\venv\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\kedro_work\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
def extract_training_data(df):
    """Extracting the training data from raw data and droping date columns
    Args=df,here raw data
    output=Dataframe"""
    df=df.drop("Date",axis=1)
    df1=df[df["RainTomorrow"].notna()]
    return df1

In [9]:
df1=extract_training_data(df)
df1

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,WNW,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,WSW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,WSW,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,E,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,NW,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,E,...,59.0,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,No
145455,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,ENE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,N,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,WNW,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,N,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No

In [10]:
df1.shape

(142193, 22)

In [11]:
def treat_missing(df1):
  """treat missing values with ffill and bfill method

  Arg=df_training_data

  output=nan values from training data get fill with the ffill and bfill method."""
  df1_treat_training_data=df1.fillna(method="ffill",axis=0).fillna(method="bfill",axis=0)
  return df1_treat_training_data

In [12]:
 df1_treat_training_data=treat_missing(df1)

In [13]:
def training_data_split(df1_treat_training_data):
  """Training data spliting ie.separating predictors and response variables.

  Arg=df_treat_training_data

  Output=Target variable get separated from main traing data."""
  X_training=df1_treat_training_data.drop(["RainTomorrow"],axis=1)
  # y_training=pd.Series(y_training)
  # X_training=pd.DataFrame(X_training)
  return X_training

In [14]:
X_training=training_data_split(df1_treat_training_data)

In [15]:
def y_training(df1_treat_training_data,X_training):
    y_training=df1_treat_training_data["RainTomorrow"]
    return y_training

In [16]:
y_training= y_training(df1_treat_training_data,X_training)

In [17]:
type(y_training)

pandas.core.series.Series

In [18]:
def lebal_encoder(X_training):
  """Lebal encoding on the discrite varibales.

  Arg=X_training 

  Output=converting categorical data into numeric variable."""

  from sklearn import preprocessing
  L_Encoder=preprocessing.LabelEncoder()
 
  X_training["Location"]=L_Encoder.fit_transform(X_training["Location"])

  X_training["WindGustDir"]=L_Encoder.fit_transform(X_training["WindGustDir"])
  X_training["WindDir9am"]=L_Encoder.fit_transform(X_training["WindDir9am"])
  X_training["WindDir3pm"]=L_Encoder.fit_transform(X_training["WindDir3pm"])
  X_training["RainToday"]=L_Encoder.fit_transform(X_training["RainToday"])
  X_training_le=X_training.copy()
  return X_training_le

In [19]:
 X_training_le=lebal_encoder(X_training)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [21]:
pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in c:\kedro_work\venv\lib\site-packages (1.2.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.17.3 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\kedro_work\venv\lib\site-packages (from scikit-learn) (3.1.0)

In [22]:
def train_test_split(X_training_le,y_training):
  """Splitting of the x_traing data into X_train,X_test,y_train,y_test data for predicting the output.

  Arg=X_training_le,y_training

  output=Get splitted data in the form of train and test data."""
  from sklearn.model_selection import train_test_split
  X_train,X_test,y_train,y_test=train_test_split(X_training_le,y_training,random_state=0,test_size=0.20)
  return X_train,X_test,y_train,y_test
X_train,X_test,y_train,y_test=train_test_split(X_training_le,y_training)

In [23]:
X_train.shape

(113754, 21)

In [24]:
X_train.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
113462,46,13.9,22.6,0.2,8.4,1.5,8,41.0,10,8,...,28.0,65.0,55.0,1013.9,1013.4,3.0,8.0,18.8,20.4,0
89638,8,22.4,29.4,2.0,6.0,6.3,1,33.0,10,1,...,24.0,71.0,59.0,1016.9,1013.1,7.0,5.0,26.4,27.5,1
138130,3,9.7,36.2,0.0,11.4,12.3,0,31.0,4,3,...,11.0,6.0,2.0,1018.1,1013.6,1.0,1.0,28.5,35.0,0
87898,8,20.5,30.1,0.0,8.8,11.1,2,37.0,10,0,...,19.0,59.0,53.0,1014.1,1010.8,2.0,3.0,27.3,29.4,0
16484,24,16.8,29.2,0.0,13.0,10.6,13,19.0,4,9,...,7.0,72.0,53.0,1021.0,1017.7,5.0,8.0,22.2,27.0,0

In [25]:
df.shape

(145460, 23)

In [26]:
X_test.shape

(28439, 21)

In [27]:
y_train.shape

(113754,)

In [28]:
y_train.head()

113462     No
89638      No
138130     No
87898      No
16484     Yes
Name: RainTomorrow, dtype: object

In [29]:
y_test.shape

(28439,)

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
def logReg(X_train,X_test,y_train,y_test):
  logreg=LogisticRegression(solver="liblinear",random_state=0)
  logreg = logreg.fit(X_train,y_train)
  return logreg

In [31]:
logreg=logReg(X_train,X_test,y_train,y_test)

In [32]:
def pred(logreg,X_train,X_test):
  y_pred_train=logreg.predict(X_train)
  y_pred_test=logreg.predict(X_test)
  return y_pred_train,y_pred_test

In [33]:
y_pred_train,y_pred_test=pred(logreg,X_train,X_test)

In [34]:
type(y_pred_train)

numpy.ndarray

In [35]:
def r2_score(y_train,y_test,y_pred_train,y_pred_test):
  """calculate r2_score

  Arg=y_pred_train,y_pred_test

  output=get r2 score to evaluate the model performance on train and test data."""
  r2_score_train=accuracy_score(y_train, y_pred_train)
  r2_score_test=accuracy_score(y_test, y_pred_test)
  return r2_score_train,r2_score_test

In [36]:
r2_score_train,r2_score_test=r2_score(y_train,y_test,y_pred_train,y_pred_test)

In [37]:
r2_score_train

0.8404100075601737

In [38]:
r2_score_test

0.8415907732339393

In [39]:
#extracting the inference data
def inference_data(df):
    """function is to extract the inference data from dataframe.
    
    Arg=df
    
    output=get inference data"""
    df=df.drop("Date",axis=1)
    inference_data=df[df["RainTomorrow"].isna()]
    return inference_data

In [32]:
inference_data=inference_data(df)

In [33]:
inference_data

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
14,Albury,8.4,24.6,0.0,NaN,NaN,NaN,NaN,S,WNW,...,57.0,32.0,1009.7,1008.7,NaN,NaN,15.9,23.5,No,NaN
283,Albury,2.6,NaN,0.0,NaN,NaN,NaN,NaN,E,WNW,...,71.0,55.0,1017.8,1017.6,NaN,6.0,9.7,14.3,No,NaN
435,Albury,22.1,35.1,0.0,NaN,NaN,NaN,NaN,ENE,SW,...,58.0,37.0,1020.9,1017.8,NaN,1.0,26.9,33.5,No,NaN
437,Albury,21.5,35.0,0.0,NaN,NaN,NaN,NaN,SSE,E,...,76.0,35.0,1015.8,1010.3,NaN,8.0,24.2,33.1,No,NaN
443,Albury,15.5,30.6,0.0,NaN,NaN,NaN,NaN,SE,SSW,...,66.0,30.0,1015.9,1013.8,NaN,NaN,19.4,30.0,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144955,Uluru,22.5,37.7,0.0,NaN,NaN,SE,50.0,SE,ESE,...,22.0,11.0,1012.6,1009.6,NaN,NaN,28.8,37.2,No,NaN
145091,Uluru,12.3,19.1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,79.0,62.0,1016.8,1014.1,8.0,8.0,15.6,18.9,No,NaN
145092,Uluru,14.2,18.7,NaN,NaN,NaN,NaN,NaN,W,NaN,...,81.0,67.0,1015.2,1014.6,8.0,8.0,16.6,17.5,NaN,NaN
145335,Uluru,13.5,NaN,0.0,NaN,NaN,NaN,NaN,ENE,SW,...,23.0,11.0,1013.7,1008.4,NaN,NaN,25.2,34.4,No,NaN
145459,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [34]:
def infer_missing_treat(inference_data):
    """function is to trate missing values in the inference data.
    Arg=inference_data
    output=missing value treatment we will fill all null values here."""
    inference_data_treat=inference_data.fillna(method="ffill",axis=0).fillna(method="bfill",axis=0)
    return inference_data_treat

In [35]:
inference_data_treat=infer_missing_treat(inference_data)

In [36]:
def inference_data_split(inference_data_treat):
  """inference data spliting ie.separating predictors and response variables.

  Arg=inference_data_treat

  Output=Target variable get separated from main traing data."""
  X_infer=inference_data_treat.drop(["RainTomorrow"],axis=1)
  return X_infer

In [37]:
 X_infer= inference_data_split(inference_data_treat)

In [38]:
 X_infer

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
14,Albury,8.4,24.6,0.0,6.4,0.0,ENE,28.0,S,WNW,...,30.0,57.0,32.0,1009.7,1008.7,6.0,6.0,15.9,23.5,No
283,Albury,2.6,24.6,0.0,6.4,0.0,ENE,28.0,E,WNW,...,13.0,71.0,55.0,1017.8,1017.6,6.0,6.0,9.7,14.3,No
435,Albury,22.1,35.1,0.0,6.4,0.0,ENE,28.0,ENE,SW,...,11.0,58.0,37.0,1020.9,1017.8,6.0,1.0,26.9,33.5,No
437,Albury,21.5,35.0,0.0,6.4,0.0,ENE,28.0,SSE,E,...,7.0,76.0,35.0,1015.8,1010.3,6.0,8.0,24.2,33.1,No
443,Albury,15.5,30.6,0.0,6.4,0.0,ENE,28.0,SE,SSW,...,11.0,66.0,30.0,1015.9,1013.8,6.0,8.0,19.4,30.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144955,Uluru,22.5,37.7,0.0,10.0,8.8,SE,50.0,SE,ESE,...,26.0,22.0,11.0,1012.6,1009.6,2.0,1.0,28.8,37.2,No
145091,Uluru,12.3,19.1,0.0,10.0,8.8,SE,50.0,SE,ESE,...,26.0,79.0,62.0,1016.8,1014.1,8.0,8.0,15.6,18.9,No
145092,Uluru,14.2,18.7,0.0,10.0,8.8,SE,50.0,W,ESE,...,26.0,81.0,67.0,1015.2,1014.6,8.0,8.0,16.6,17.5,No
145335,Uluru,13.5,18.7,0.0,10.0,8.8,SE,50.0,ENE,SW,...,7.0,23.0,11.0,1013.7,1008.4,8.0,8.0,25.2,34.4,No
145459,Uluru,14.9,18.7,0.0,10.0,8.8,SE,50.0,ESE,ESE,...,17.0,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No

In [39]:
def lebal_encoder(X_infer):
  """Lebal encoding on the discrite varibales.

  Arg=X_training 

  Output=converting categorical data into numeric variable."""


  from sklearn import preprocessing
  L_Encoder=preprocessing.LabelEncoder()
  X_infer["Location"]=L_Encoder.fit_transform(X_infer["Location"])

  X_infer["WindGustDir"]=L_Encoder.fit_transform(X_infer["WindGustDir"])
  X_infer["WindDir9am"]=L_Encoder.fit_transform(X_infer["WindDir9am"])
  X_infer["WindDir3pm"]=L_Encoder.fit_transform(X_infer["WindDir3pm"])
  X_infer["RainToday"]=L_Encoder.fit_transform(X_infer["RainToday"])
  X_infer_le=X_infer.copy()
  return X_infer_le

In [40]:
X_infer_le=lebal_encoder(X_infer)
X_infer_le

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
14,2,8.4,24.6,0.0,6.4,0.0,1,28.0,8,14,...,30.0,57.0,32.0,1009.7,1008.7,6.0,6.0,15.9,23.5,0
283,2,2.6,24.6,0.0,6.4,0.0,1,28.0,0,14,...,13.0,71.0,55.0,1017.8,1017.6,6.0,6.0,9.7,14.3,0
435,2,22.1,35.1,0.0,6.4,0.0,1,28.0,1,12,...,11.0,58.0,37.0,1020.9,1017.8,6.0,1.0,26.9,33.5,0
437,2,21.5,35.0,0.0,6.4,0.0,1,28.0,10,0,...,7.0,76.0,35.0,1015.8,1010.3,6.0,8.0,24.2,33.1,0
443,2,15.5,30.6,0.0,6.4,0.0,1,28.0,9,11,...,11.0,66.0,30.0,1015.9,1013.8,6.0,8.0,19.4,30.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144955,38,22.5,37.7,0.0,10.0,8.8,9,50.0,9,2,...,26.0,22.0,11.0,1012.6,1009.6,2.0,1.0,28.8,37.2,0
145091,38,12.3,19.1,0.0,10.0,8.8,9,50.0,9,2,...,26.0,79.0,62.0,1016.8,1014.1,8.0,8.0,15.6,18.9,0
145092,38,14.2,18.7,0.0,10.0,8.8,9,50.0,13,2,...,26.0,81.0,67.0,1015.2,1014.6,8.0,8.0,16.6,17.5,0
145335,38,13.5,18.7,0.0,10.0,8.8,9,50.0,1,12,...,7.0,23.0,11.0,1013.7,1008.4,8.0,8.0,25.2,34.4,0
145459,38,14.9,18.7,0.0,10.0,8.8,9,50.0,2,2,...,17.0,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,0